services:
    db:
        image: postgres:17
        restart: unless-stopped
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./prisma:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
        deploy:
            endpoint_mode: dnsrr
            mode: replicated
            replicas: 10
        env_file: ".env"
        # ports:
        #     - 4000:3000

    proxy:
        image: nginx:1.27.2
        depends_on:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/m7011e.maxlu.cloud/fullchain.pem:/root/fullchain.pem
            - /etc/letsencrypt/live/m7011e.maxlu.cloud/privkey.pem:/root/privkey.pem
        ports:
            - 80:80
            - 443:443

volumes:
    postgres-data:
